### ISSUE TITLE
Readme assumes NVM is installed even though it does not ship with Node.js

### ISSUE THREAD

**Issue by Basssiiie** [wisnia74/openrct2-typescript-mod-template#266]
Hey, 

In step 6 of the installation chapter of the readme ([here](https://github.com/wisnia74/openrct2-typescript-mod-template#installation)) the user is asked to run `nvm use`, but this command-line program is not mentioned anywhere else in the readme and does not ship with Node.js mentioned in step 1, so for most users this would return a "command not found" error.

Thank you for your time. 🙂

**Comment by wisnia74** [comment]
Hi! Sorry that response took so long. I haven't updated the repo in quite some time and I think I won't be anymore, unfortunately I don't really have time for that.

It will remain here as a modders resource, feel free to use any part you need. Thanks!
