### ISSUE TITLE
If npm run init fails, it cannot be run a second time

### ISSUE THREAD

**Issue by Basssiiie** [wisnia74/openrct2-typescript-mod-template#267]
Hey,

If you run `npm run init` and it fails due to an error, it cannot be run again because the `init` gulp script is deleted from the gulp directory. 

In my case I skipped step 3 because I just wanted it to download `openrct2.d.ts` automatically (because the Readme said that is what it does). But when you do this, it errors because the `MOD_URL` is not a valid url yet. After that, it's not possible to run `npm run init` a second time because the gulp `init` script has already been deleted from disk.

Thank you for your time! 🙂

**Comment by wisnia74** [comment]
Hi! Sorry that response took so long. I haven't updated the repo in quite some time and I think I won't be anymore, unfortunately I don't really have time for that.

It will remain here as a modders resource, feel free to use any part you need. Thanks!
