### ISSUE TITLE
Project full of lint errors and VS Code underlines entire files

### ISSUE THREAD

**Issue by Basssiiie** [wisnia74/openrct2-typescript-mod-template#268]
Hey,

When opening the template in VS Code, the project goes crazy with many lint errors, even after I already went through all installation steps.

![image](https://user-images.githubusercontent.com/20048660/235316529-3120069f-67b1-4d1c-a39f-2c38684eab0b.png)

`npm run lint` also returns all these errors.

Thank you for your time. 🙂

**Comment by Basssiiie** [comment]
Update: restarting VS Code seemed to have fixed some of the errors and warnings, but the following ones still remain:
```
warning  Unexpected console statement  no-console
error    Delete `␍`                    prettier/prettier
```

I'd say these should be ignored in the respective ignore-files, or fixed?

**Comment by wisnia74** [comment]
Hi! Sorry that response took so long. I haven't updated the repo in quite some time and I think I won't be anymore, unfortunately I don't really have time for that.

It will remain here as a modders resource, feel free to use any part you need. Thanks!
