### ISSUE TITLE
Property 'targetApiVersion' is missing in type but required in type 'PluginMetadata'

### ISSUE THREAD

**Issue by Basssiiie** [wisnia74/openrct2-typescript-mod-template#269]
Hey,

Running any of the NPM `start` or `build` commands causes the following Typescript warning:
```
(!) Plugin typescript: @rollup/plugin-typescript TS2345: Argument of type '{ name: string; version: string; authors: string[]; type: "local"; licence: string; main: () => void; }' is not assignable to parameter of type 'PluginMetadata'.
  Property 'targetApiVersion' is missing in type '{ name: string; version: string; authors: string[]; type: "local"; licence: string; main: () => void; }' but required in type 'PluginMetadata'.
```

This missing field was added [here](https://github.com/OpenRCT2/OpenRCT2/pull/18869) last December and is now required by the interface for new plugins.

Thank you for your time. 🙂

**Comment by wisnia74** [comment]
Hi! Sorry that response took so long. I haven't updated the repo in quite some time and I think I won't be anymore, unfortunately I don't really have time for that.

It will remain here as a modders resource, feel free to use any part you need. Thanks!
