### ISSUE TITLE
Externally imported NPM dependencies do not get shipped in plugin

### ISSUE THREAD

**Issue by Basssiiie** [wisnia74/openrct2-typescript-mod-template#270]
Hey,

Externally installed NPM packages (like for example my [FlexUI](https://www.npmjs.com/package/openrct2-flexui/v/0.1.0-prerelease.12) library) do not get shipped with plugins using this template.

After installing FlexUI using `npm install openrct2-flexui@next` and using this script:
```ts
import { window } from 'openrct2-flexui';

function main(): void
{
  const w = window({
    width: 100, height: 100, content: []
  });

  w.open();
}

export default main;
```
The output from `npm run build:dev` for the `main` function is as follows (trimmed and beautified for readability):
```js
var openrct2Flexui=require('openrct2-flexui');
function main(){
  var w=openrct2Flexui.window({
    width:100,
    height:100,content:[]
  });
  w.open()
}
```
And the following errors have occured during the build:
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
openrct2-flexui (imported by src/main.ts)
```
At last, when using the plugin ingame, the plugin crashes because the `require()` function could not be found.

I would guess the expected behaviour would be to have the used functions from FlexUI be inlined into the output file. 

Thank you for your time. 🙂

**Comment by wisnia74** [comment]
Hi! Sorry that response took so long. I haven't updated the repo in quite some time and I think I won't be anymore, unfortunately I don't really have time for that.

It will remain here as a modders resource, feel free to use any part you need. Thanks!
